### ISSUE TITLE
Offline data

### ISSUE THREAD

**Issue by GuLinux** [Stellarium/stellarium-web-engine#1]
Hi,
I'm looking into integrating stellarium-web-engine into my astrophotography web application: https://github.com/GuLinux/StarQuew

However my main concern is that stellarium-web-engine requires access to `data.stellarium.org`, and I saw this hostname is hardcoded into the sources.
The ideal usage of my StarQuew application though is mainly for local installation, for instance on a raspberry pi on the field, without internet access.
Hence my 2 questions:
1) Could it be possible to download and have a local mirror of this data? Is there any licence restriction?
2) If 1) is possible, could you make the data source uri a configurable parameter?
Thanks,
Marco

**Comment by xalioth** [comment]
Hi Marco,

stellarium web engine require also access to

**Comment by xalioth** [comment]
Hi Marco,

currently there is no easy way to get all the data from data.stellarium.org (it's very large, especially the Gaia stars files). The DSS data is also not hosted by us, but by the CDS, and has licencing restrictions (http://archive.stsci.edu/dss/copyright.html) (and it's also a huge data set!). We are working on making it easier to configure the URL though, and also potentially to use more limited data sets so that it can be shipped as an offline DB. This is something we need to do at some point if we want to create an offline version of Stellarium Web Engine, which is one of our (long term) goal.

StarQuew looks very interesting, in the longer term I was also hoping we can add such features in Stellarium Web. We are however currently very busy with the new engine itself so it's not on our highest priority list. I'm currently trying to make a kind of plugin system, so that users can add such features to Stellarium Web easily, but again this is work in progress.

Fabien
