### ISSUE TITLE
Adding CCD FOV calculator feature for stellarium-web

### ISSUE THREAD

**Issue by Abelink23** [Stellarium/stellarium-web-engine#11]
Dear developers,

I would like to ask for a CCD field of view calculator on the new stellarium-web that could be used by all the community of astrophotographers to plan their sessions. Just like another set of input parameters in "Observation with Eyes/Binoculars/Telescope", a four tab called CCD could be added. 

Input parameters could be the X/Y field of view and rotation, or more detailed, including the CCD resolution, pixel size, focal length of the telescope, and eventually, the aperture. 

Output parameters could be (apart from plotting the FOV on the sky): the plate scale, field of view, resolving power.

As a reference, it could be similar to what provided by this website, in the "Imaging mode" tab: http://astronomy.tools/calculators/field_of_view/

Many thanks,
Abel de Burgos
Support Astronomer for the Nordic Optical Telescope.

**Comment by xalioth** [comment]
Hi Abel,

thanks for the request. Yes it's something I plan to add beside the existing observation features. I'm very busy with other topics right now so don't expect this to be available very soon though..

Fabien

**Comment by am17107** [comment]
@xalioth hello fabien i will ask to you i can implment the new atmosphere for stellarium web even i editing the files the atmosphere improve to te terrestrial atmosphere is that in github da to implement okay  I'm just asking a question for you if i can edit files of stellarium web

**Comment by am17107** [comment]
@gzotti I can explain better for you to understand me i m not flooding this problem if i want edit files on github i can i will implemement it you can reply me I only write once in a while I'm not trolling and waste my time 
I will learn to implement this for the stellarium web I'm thinking github implements this it's easy for me to deploy some files to stellarium web I'll make it all myself
I'm asking the right question i'll try to implement the atmosphere for the stellarium web and then the new landscape the clouds and lightning storms rains city wolf wind thunder sounds cars passing and pole lights and birds houses churches and oceans with water flying insects moon halo and trees I will learn how to create all this for one application I know you work at it I can implement all this myself even though you are working on it I will create everything myself for stellarium web now i'm creating everything I'm making it all happen my great possibility is gave build the atmosphere the landscape the clouds trying easily on github even if i edited it on github the whole atmosphere could be updated if i completed this process it would be easy i see this i would be happy with this model when i start the process editing stellarium web files i will implement my new sky to be able to see the real sky is the prettiest simulation including lightning wind thunderstorms pollution and clear sky I will build this if you allow i will make it all work on stellarium web myself and i just want to edit a file so i can build an atmosphere who i saw build it myself this work is done by us and by all people                  I don't like animation              i will make it all work on stellarium web myself and i just want to edit a Brunetons-Improved-Atmospheric-Scattering
This is a port to Unity of a updated and improved version of Brunetons atmospheric scatter published in 2017. The original was published in 2008 so is a bit old now.

The new version contains the follow improvements.

More descriptive function and variable names and extensive comments.  light of sun and shadow earth                                                                       
                                              

Improved texture coordinate mapping which removes the horizon artifact in the previous version.

Provides a option to store the single Mie scatter in the alpha channel (Rayleigh is in the rgb) or in the rgb of a separate texture.

Provides a example of how to combine with light shafts.

Converts the spectral radiance values to RGB luminance values as described in A Qualitative and Quantitative Evaluation of 8 Clear Sky Models (section 14.3)

Or precomputes luminance values instead of spectral radiance values, as described in Real-time Spectral Scattering in Large-scale Natural Participating Media (section 4.4). The precomputation phase is then slower than with the above option, but uses the same amount of GPU memory.

Adds support for the ozone layer, and for custom density profiles for air molecules and aerosols.

The demo uses a image effect shader as a example of how to use the scattering. The sphere rendered and its light shafts are hard coded into the shader as its just a example. Some work would be needed to convert this into a practical implementation

file so i can build an atmosphere who i saw build it myself this work is done by us and by all people                                                                                                                                                                                                                                                                                                             
                                                                                             light of sun and shadow earth                                                                       
                                                                                                                                                                   
                                                                                                                                                                   
                                                                                                                                       i will not write anymore                              I'll be back next year to write in march 7th 2020

**Comment by am17107** [comment]
@xalioth hello fabien my name is alexandre i can implement the atmosphere on github

**Comment by vpicouet** [comment]
Hello,
I did not find how to add a particular FOV to stellarium web, is is described in any documentation?
Thanks for the help!
