### ISSUE TITLE
The sunrise and sunset time for Great Falls Montana August 13, 1959 is incorrect.

### ISSUE THREAD

**Issue by Thatisfunny** [Stellarium/stellarium-web-engine#73]
The sunrise and sunset time for Great Falls Montana August 13, 1959 is incorrect. 
Please resolve.
Thank you!

**Comment by gzotti** [comment]
That is funny, indeed. What exactly have you done to come to this conclusion? When was sunrise, what did the program say? Is this a time zone issue? Did time zones change between 1959 and today?

**Comment by xalioth** [comment]
Hi, could you please give us more data so that we can analyze and reproduce the issue. We'd need the maybe a screenshot, the expected rise/set time etc. Thanks

**Comment by Thatisfunny** [comment]
Hi, thank you for your responses.  I hope these pictures help.  This happens with many other places I search as well (the sun will rise at a time that isn't its actual sunrise time).  I appreciate your help.  ![great falls montana stellarium](https://user-images.githubusercontent.com/74025658/100359834-18246300-2fc6-11eb-8961-b6f429ff468b.jpg)
![great falls montana sunrise and sunset](https://user-images.githubusercontent.com/74025658/100359890-2e322380-2fc6-11eb-84e4-e2cf84999c2a.jpg)

**Comment by xalioth** [comment]
I think the reason is that the web version doesn't change it's time zone to
the one used at the location you pickedup, but rather always use your real
local timezone (where your computer is located). The the error lays in the
displayed time rather than in the astronomical computations.

This timezone behaviour is not ideal, and this is a know issue,

thanks!

Fabien
